button:
  -
    name: "销售展厅"
    sub_button:
      -
        type: "view"
        name: "最新资讯"
        url: "http://thxl.memeing.cn/page/news"
      -
        type: "view"
        name: "在售车型"
        url: "http://thxl.memeing.cn/cars"
      -
        type: "view"
        name: "优惠促销"
        url: "http://thxl.memeing.cn/page/youhui"
      -
        type: "view"
        name: "车展团购报名"
        url: "http://thxl.memeing.cn/page/tuangou"
      -
        type: "view"
        name: "联系销售"
        url: "http://thxl.memeing.cn/contact/show"

  -
    name: "售后服务"
    sub_button:
      -
        type: "view"
        name: "24小时救援"
        url: "http://thxl.memeing.cn/page/jiuyuan"
      -
        type: "view"
        name: "预约保养"
        url: "http://thxl.memeing.cn/order/care"
      -
        type: "view"
        name: "金领结服务"
        url: "http://m.chevrolet.com.cn/service.html"
      -
        type: "view"
        name: "保养促销"
        url: "http://thxl.memeing.cn/page/baoyang"
      -
        type: "view"
        name: "满意度评价"
        url: "http://thxl.memeing.cn/evaluates/new"

  -
    name: "车主之家"
    sub_button:
      -
        type: "view"
        name: "车主关怀"
        url: "http://thxl.memeing.cn/tool/care"
      -
        type: "view"
        name: "违章查询"
        url: "http://thxl.memeing.cn/tool/weizhang"
      -
        type: "view"
        name: "潮人堂会员"
        url: "http://www.xici.net/b1285899/"
      -
        type: "view"
        name: "车主活动"
        url: "http://thxl.memeing.cn/page/huodong"
      -
        type: "view"
        name: "MyChavy"
        url: "http://www.chevrolet.com.cn/aftersales_app/direct-download.html"