button:
  -
    name: "销售展厅"
    sub_button:
      -
        type: "view"
        name: "最新资讯"
        url: "http://thxl.memeing.cn/"
      -
        type: "view"
        name: "在售车型"
        url: "http://thxl.memeing.cn/cars"
      -
        type: "view"
        name: "优惠促销"
        url: "http://thxl.memeing.cn/"
      -
        type: "view"
        name: "车展团购报名"
        url: "http://thxl.memeing.cn/"
      -
        type: "view"
        name: "联系销售"
        url: "http://thxl.memeing.cn/"

  -
    name: "售后服务"
    sub_button:
      -
        type: "view"
        name: "24小时救援"
        url: "http://thxl.memeing.cn/"
      -
        type: "view"
        name: "预约保养"
        url: "http://thxl.memeing.cn/"
      -
        type: "view"
        name: "金领结服务"
        url: "http://thxl.memeing.cn/"
      -
        type: "view"
        name: "常用配件查询"
        url: "http://thxl.memeing.cn/"
      -
        type: "view"
        name: "保养促销"
        url: "http://thxl.memeing.cn/"

  -
    name: "车主之家"
    sub_button:
      -
        type: "view"
        name: "爱车提醒"
        url: "http://thxl.memeing.cn/"
      -
        type: "view"
        name: "违章查询"
        url: "http://thxl.memeing.cn/"
      -
        type: "view"
        name: "潮人堂会员"
        url: "http://thxl.memeing.cn/"
      -
        type: "view"
        name: "车主活动"
        url: "http://thxl.memeing.cn/"
      -
        type: "view"
        name: "MyChavy"
        url: "http://thxl.memeing.cn/"